# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 19:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('email_registration', '0002_auto_20170215_1924'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
    ]
